# Site settings
title: fabs-hh
logo: /images/fabs-hh.png
email: mary@vomar.de
description: > # this means to ignore newlines until "baseurl:"
 fabs-hh (fabulous frontend labs) - for everyone who is interested in frontend topics
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
#twitter_username:
#github_username:

# Build settings
markdown: kramdown
